/**
 * seed 곡의 YouTube Topic 채널 (embed-safe) 버전 자동 검색
 *
 *   YOUTUBE_API_KEY=... npx tsx scripts/catalog/findTopicIds.ts
 *   YOUTUBE_API_KEY=... npx tsx scripts/catalog/findTopicIds.ts --apply
 *
 * --apply: 찾은 Topic ID를 replacements.json에 자동 기록
 *
 * 우선순위:
 *   1. "- Topic" 채널 (auto-generated by YouTube)
 *   2. "Official Audio" 제목
 *   3. "Provided to YouTube" 설명
 *   4. videoEmbeddable=true 필터
 *
 * 제외:
 *   - MV, VEVO, fan upload, lyrics video, performance clip
 */
import 'dotenv/config';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { ALL_SEED_TRACKS } from '../../src/data/seeds';
import { checkEmbeddableViaApi } from '../lib/youtubePlaybackVerify';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPORT_DIR = join(__dirname, '../reports');
const REPLACEMENTS_PATH = join(__dirname, '../../src/data/seeds/replacements.json');
const META_PATH = join(__dirname, '../../src/data/seeds/catalogMeta.json');
const RESULT_PATH = join(REPORT_DIR, 'topic-id-search-results.json');

const apiKey =
  process.env.YOUTUBE_API_KEY?.trim() ||
  process.env.EXPO_PUBLIC_YOUTUBE_API_KEY?.trim();

const applyMode = process.argv.includes('--apply');

function sleep(ms: number) {
  return new Promise((r) => setTimeout(r, ms));
}

const EXCLUDE_PATTERNS = [
  /\bMV\b/i,
  /\bM\/V\b/i,
  /music\s*video/i,
  /\bVEVO\b/i,
  /\bfan\b/i,
  /\bcover\b/i,
  /\blyrics?\b/i,
  /\bperformance\b/i,
  /\blive\b/i,
  /\breaction\b/i,
  /\btutorial\b/i,
  /\bdance\s*practice\b/i,
];

const PREFER_PATTERNS = [
  { pattern: /- Topic$/i, score: 100 },
  { pattern: /official\s*audio/i, score: 80 },
  { pattern: /provided to youtube/i, score: 70 },
  { pattern: /auto-generated/i, score: 60 },
  { pattern: /audio\s*only/i, score: 50 },
];

type SearchCandidate = {
  youtubeId: string;
  title: string;
  channelTitle: string;
  score: number;
  isTopicChannel: boolean;
  isOfficialAudio: boolean;
  embeddable: boolean | null;
};

type TrackResult = {
  originalId: string;
  artist: string;
  title: string;
  category: string;
  candidates: SearchCandidate[];
  bestCandidate: SearchCandidate | null;
  status: 'found' | 'no_candidates' | 'error' | 'already_safe';
};

async function searchTopicVersion(
  artist: string,
  title: string,
  key: string
): Promise<SearchCandidate[]> {
  const queries = [
    `${artist} ${title} topic`,
    `${artist} ${title} official audio`,
    `${artist} ${title} provided to youtube`,
  ];

  const allCandidates = new Map<string, SearchCandidate>();

  for (const q of queries) {
    const url = new URL('https://www.googleapis.com/youtube/v3/search');
    url.searchParams.set('part', 'snippet');
    url.searchParams.set('q', q);
    url.searchParams.set('type', 'video');
    url.searchParams.set('videoEmbeddable', 'true');
    url.searchParams.set('maxResults', '5');
    url.searchParams.set('key', key);

    try {
      const res = await fetch(url);
      if (!res.ok) continue;
      const data = (await res.json()) as {
        items?: Array<{
          id?: { videoId?: string };
          snippet?: { title?: string; channelTitle?: string; description?: string };
        }>;
      };

      for (const item of data.items ?? []) {
        const vid = item.id?.videoId;
        if (!vid || allCandidates.has(vid)) continue;

        const t = item.snippet?.title ?? '';
        const ch = item.snippet?.channelTitle ?? '';
        const desc = item.snippet?.description ?? '';
        const fullText = `${t} ${ch} ${desc}`;

        const excluded = EXCLUDE_PATTERNS.some((p) => p.test(t));
        if (excluded) continue;

        let score = 0;
        for (const { pattern, score: s } of PREFER_PATTERNS) {
          if (pattern.test(fullText)) score += s;
        }

        const isTopicChannel = /- Topic$/i.test(ch);
        const isOfficialAudio = /official\s*audio/i.test(t);

        if (isTopicChannel) score += 50;
        if (isOfficialAudio) score += 30;

        allCandidates.set(vid, {
          youtubeId: vid,
          title: t,
          channelTitle: ch,
          score,
          isTopicChannel,
          isOfficialAudio,
          embeddable: null,
        });
      }
    } catch {
      /* skip */
    }
    await sleep(200);
  }

  const sorted = [...allCandidates.values()].sort((a, b) => b.score - a.score);

  for (const c of sorted.slice(0, 3)) {
    const { result } = await checkEmbeddableViaApi(c.youtubeId, key);
    c.embeddable = result === 'embeddable';
    await sleep(150);
  }

  return sorted;
}

async function main() {
  if (!apiKey) {
    console.error('YOUTUBE_API_KEY 환경변수를 설정하세요.');
    process.exit(1);
  }

  console.log('\n=== Topic ID Finder (Embed-Safe) ===\n');
  console.log(`Tracks: ${ALL_SEED_TRACKS.length}`);
  if (applyMode) console.log('--apply mode: replacements.json에 자동 기록');
  console.log('');

  const results: TrackResult[] = [];
  let found = 0;
  let alreadySafe = 0;

  for (let i = 0; i < ALL_SEED_TRACKS.length; i++) {
    const track = ALL_SEED_TRACKS[i];
    const category = track.id.replace(/^seed-/, '').replace(/-.*$/, '');
    process.stdout.write(`[${i + 1}/${ALL_SEED_TRACKS.length}] ${track.artist} - ${track.title}… `);

    const { result: currentEmbed } = await checkEmbeddableViaApi(track.youtubeId, apiKey);
    await sleep(150);

    if (currentEmbed === 'embeddable') {
      console.log('✅ already embeddable');
      results.push({
        originalId: track.youtubeId,
        artist: track.artist,
        title: track.title,
        category,
        candidates: [],
        bestCandidate: null,
        status: 'already_safe',
      });
      alreadySafe++;
      continue;
    }

    const candidates = await searchTopicVersion(track.artist, track.title, apiKey);
    const best = candidates.find((c) => c.embeddable) ?? candidates[0] ?? null;

    if (best && best.embeddable) {
      console.log(`🔄 → ${best.youtubeId} [${best.channelTitle}] (score=${best.score})`);
      found++;
    } else if (best) {
      console.log(`⚠️ → ${best.youtubeId} (embed 미확인)`);
    } else {
      console.log('❌ 후보 없음');
    }

    results.push({
      originalId: track.youtubeId,
      artist: track.artist,
      title: track.title,
      category,
      candidates,
      bestCandidate: best,
      status: best?.embeddable ? 'found' : candidates.length ? 'no_candidates' : 'error',
    });

    await sleep(300);
  }

  // ── 결과 저장 ──
  mkdirSync(REPORT_DIR, { recursive: true });
  writeFileSync(RESULT_PATH, JSON.stringify(results, null, 2), 'utf8');

  console.log('\n--- Summary ---');
  console.log(`Already safe: ${alreadySafe}`);
  console.log(`Found topic: ${found}`);
  console.log(`No candidate: ${results.filter((r) => r.status === 'no_candidates').length}`);
  console.log(`Error: ${results.filter((r) => r.status === 'error').length}`);

  // ── --apply: replacements.json + catalogMeta.json 자동 업데이트 ──
  if (applyMode) {
    const repFile = JSON.parse(readFileSync(REPLACEMENTS_PATH, 'utf8')) as {
      replacements: Record<string, unknown>;
    };
    const metaFile = JSON.parse(readFileSync(META_PATH, 'utf8')) as {
      byYoutubeId: Record<string, Record<string, unknown>>;
    };
    const now = new Date().toISOString();
    let applied = 0;
    let disabled = 0;

    for (const r of results) {
      if (r.status === 'already_safe') {
        metaFile.byYoutubeId[r.originalId] = {
          ...metaFile.byYoutubeId[r.originalId],
          verifiedAt: now,
          verifiedStatus: 'playable',
          severity: 'info',
          disabled: false,
        };
        continue;
      }

      metaFile.byYoutubeId[r.originalId] = {
        ...metaFile.byYoutubeId[r.originalId],
        verifiedAt: now,
        verifiedStatus: 'embedding_restricted',
        severity: 'critical',
        disabled: true,
        disabledReason: 'embedding_restricted',
      };
      disabled++;

      if (r.bestCandidate?.embeddable && !repFile.replacements[r.originalId]) {
        repFile.replacements[r.originalId] = {
          reason: 'topic_channel_replacement',
          replacement: {
            youtubeId: r.bestCandidate.youtubeId,
          },
        };
        applied++;
      }
    }

    writeFileSync(
      REPLACEMENTS_PATH,
      JSON.stringify(repFile, null, 2) + '\n',
      'utf8'
    );
    writeFileSync(
      META_PATH,
      JSON.stringify(
        {
          $comment: '운영 메타 — disabled/verifiedAt. verify:tracks:playback 후 npm run seed:sync-meta',
          byYoutubeId: metaFile.byYoutubeId,
        },
        null,
        2
      ) + '\n',
      'utf8'
    );

    console.log(`\n✅ Applied: ${applied} replacements, ${disabled} disabled`);
  }

  console.log(`\nFull results: ${RESULT_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
