import { buildSeedTracks } from './helpers';
import type { Track } from '@/types/track';

const TAGS = ['멍', '잔잔한', '배경'];

/** 멍때리기 — energy 1~4 */
export const BLANK_SEED_TRACKS: Track[] = buildSeedTracks('blank', TAGS, [
  // ── embed-safe: indie / instrumental ──
  { title: 'Stay', artist: 'The Kid LAROI & Justin Bieber', youtubeId: 'kTJczUoc26U', energyLevel: 3, noveltyTier: 'familiar' },
  { title: 'Sunset Lover', artist: 'Petit Biscuit', youtubeId: '9VxqDxDLVKc', energyLevel: 2, noveltyTier: 'familiar', moodTags: ['인스트'] },
  { title: 'Weightless', artist: 'Marconi Union', youtubeId: 'UfcAVejslrU', energyLevel: 1, noveltyTier: 'familiar', moodTags: ['인스트'] },
  { title: 'River Flows in You', artist: 'Yiruma', youtubeId: '7maJZk3YX6w', energyLevel: 2, noveltyTier: 'familiar', moodTags: ['인스트'] },
  { title: 'Dreams', artist: 'Fleetwood Mac', youtubeId: 'mrZRURw1y3E', energyLevel: 3, noveltyTier: 'familiar' },
  { title: 'Glimpse of Us', artist: 'Joji', youtubeId: 'FB3pG2nr5UM', energyLevel: 2, noveltyTier: 'mid' },
  { title: 'Until I Found You', artist: 'Stephen Sanchez', youtubeId: 'Gk3PicCBfn4', energyLevel: 3, noveltyTier: 'mid' },
  { title: 'lazy', artist: 'Kozy', youtubeId: 'd6FyU3Ys6kY', energyLevel: 2, noveltyTier: 'hidden', moodTags: ['로파이'] },
  { title: 'Coffee', artist: 'beabadoobee', youtubeId: 'CjvRfUvsmuQ', energyLevel: 2, noveltyTier: 'hidden' },
  { title: 'Soda Pop', artist: 'The Marías', youtubeId: '5QOQb3a2y6o', energyLevel: 2, noveltyTier: 'hidden' },
  // ── embed-safe: Topic 채널 (auto-generated by YouTube) ──
  { title: 'Yellow', artist: 'Coldplay', youtubeId: '9qnqYL0eNNI', energyLevel: 3, noveltyTier: 'familiar' },
  // ── embed 검증 필요 (verify:embed → Topic ID 자동 교체) ──
  { title: 'Chewing Gum', artist: 'NCT DREAM', youtubeId: 'y6pP2YdJmIA', energyLevel: 3, noveltyTier: 'familiar' },
  { title: 'Softly', artist: 'NCT DREAM', youtubeId: '0qanF7wGdW8', energyLevel: 2, noveltyTier: 'familiar' },
  { title: 'Mikrokosmos', artist: 'BTS', youtubeId: '1y6smkhT0X4', energyLevel: 3, noveltyTier: 'familiar' },
  { title: 'Peaches', artist: 'Justin Bieber', youtubeId: 'tQ0yjYUFK0Q', energyLevel: 3, noveltyTier: 'mid' },
  { title: 'Best Part', artist: 'H.E.R.', youtubeId: 'vBy7FaapGRo', energyLevel: 2, noveltyTier: 'mid' },
  { title: 'Come Back Home', artist: 'SEVENTEEN', youtubeId: 'hqgaTnqxv0Y', energyLevel: 3, noveltyTier: 'mid' },
  { title: '밤편지', artist: '아이유', youtubeId: 'BzYnNdJhZQw', energyLevel: 2, noveltyTier: 'mid', moodTags: ['새벽'] },
]);
