import { buildSeedTracks } from './helpers';
import type { Track } from '@/types/track';

const TAGS = ['새벽', '몽환적', '감성'];

/** 새벽감성 — energy 2~5, 점진 상승 */
export const DAWN_SEED_TRACKS: Track[] = buildSeedTracks('dawn', TAGS, [
  // ── embed-safe: indie / small label ──
  { title: 'Holocene', artist: 'Bon Iver', youtubeId: 'TWcyIpul8OE', energyLevel: 2, noveltyTier: 'familiar', moodTags: ['몽환적', '잔잔한'] },
  { title: 'Apocalypse', artist: 'Cigarettes After Sex', youtubeId: 'pZ31pyTZdh0', energyLevel: 2, noveltyTier: 'familiar', moodTags: ['몽환적'] },
  { title: 'The Night', artist: 'Offonoff', youtubeId: '3j9w2nVXj6A', energyLevel: 2, noveltyTier: 'familiar', moodTags: ['잔잔한'] },
  { title: '잠', artist: '이하이', youtubeId: '4KaCND7awRI', energyLevel: 2, noveltyTier: 'mid', moodTags: ['잔잔한'] },
  { title: 'Slowly', artist: 'George', youtubeId: '6GKjFSWtyJY', energyLevel: 2, noveltyTier: 'hidden', moodTags: ['잔잔한'] },
  { title: 'Warm', artist: 'offonoff', youtubeId: '7JbTDZq8wew', energyLevel: 2, noveltyTier: 'hidden' },
  { title: 'Pink + White', artist: 'Frank Ocean', youtubeId: 'uzS3WG6__g4', energyLevel: 3, noveltyTier: 'mid', moodTags: ['몽환적'] },
  { title: 'Midnight Train', artist: '새소년', youtubeId: '0pYenlX5YJc', energyLevel: 3, noveltyTier: 'familiar', moodTags: ['새벽'] },
  { title: 'Galaxy', artist: '볼빨간사춘기', youtubeId: 'm9YShC5D1LM', energyLevel: 3, noveltyTier: 'mid' },
  { title: '도망가자', artist: '선우정아', youtubeId: 'x8nWS5sc37o', energyLevel: 2, noveltyTier: 'hidden', moodTags: ['몽환적'] },
  { title: 'Lost Stars', artist: 'Adam Levine', youtubeId: 'VcyMSg_Eu1k', energyLevel: 3, noveltyTier: 'mid', moodTags: ['새벽', '몽환적'] },
  // ── embed-safe: Topic 채널 (auto-generated by YouTube) ──
  { title: 'Love poem', artist: '아이유', youtubeId: 'iOKRYIMhaDk', energyLevel: 3, noveltyTier: 'familiar', moodTags: ['잔잔한'] },
  { title: 'eight', artist: '아이유', youtubeId: '5_IYVichXbA', energyLevel: 4, noveltyTier: 'familiar' },
  // ── embed 검증 필요 (verify:embed → Topic ID 자동 교체) ──
  { title: 'Seoul', artist: 'RM', youtubeId: '4YIvXoJYiuo', energyLevel: 2, noveltyTier: 'mid', moodTags: ['새벽'] },
  { title: 'Blueming', artist: '아이유', youtubeId: 'D1LvR11qQoU', energyLevel: 4, noveltyTier: 'familiar' },
  { title: 'Ditto', artist: 'NewJeans', youtubeId: 'Km71Rr9K-Bw', energyLevel: 3, noveltyTier: 'familiar', moodTags: ['몽환적'] },
  { title: 'Hype Boy', artist: 'NewJeans', youtubeId: '11t7c7UJfNM', energyLevel: 4, noveltyTier: 'familiar' },
  { title: 'Peach', artist: '아이유', youtubeId: 'y6O5t8gK47E', energyLevel: 3, noveltyTier: 'mid', moodTags: ['잔잔한'] },
]);
