import { buildSeedTracks } from './helpers';
import type { Track } from '@/types/track';

const TAGS = ['집중', '몰입'];

/** 집중 — energy 5~8 */
export const FOCUS_SEED_TRACKS: Track[] = buildSeedTracks('focus', TAGS, [
  // ── embed-safe: instrumental / indie ──
  { title: 'Time', artist: 'Hans Zimmer', youtubeId: 'RxabLA7UQ9k', energyLevel: 6, noveltyTier: 'familiar', moodTags: ['인스트'] },
  { title: 'Experience', artist: 'Ludovico Einaudi', youtubeId: 'hN_q-_nGUG4', energyLevel: 5, noveltyTier: 'familiar', moodTags: ['인스트'] },
  { title: 'We Can Make the World Stop', artist: 'The Glitch Mob', youtubeId: 'qJh9VlDPl8U', energyLevel: 7, noveltyTier: 'mid', moodTags: ['인스트'] },
  // ── embed-safe: Topic 채널 (auto-generated by YouTube) ──
  { title: 'ON (Feat. Sia)', artist: 'BTS', youtubeId: 'AlwmaGcMjNE', energyLevel: 8, noveltyTier: 'familiar' },
  // ── embed 검증 필요 (verify:embed → Topic ID 자동 교체) ──
  { title: 'Dynamite', artist: '방탄소년단', youtubeId: 'gdZLi9oWNZg', energyLevel: 7, noveltyTier: 'familiar' },
  { title: 'God\'s Menu', artist: 'Stray Kids', youtubeId: 'TQTlCHxyuu8', energyLevel: 8, noveltyTier: 'familiar' },
  { title: 'Next Level', artist: 'aespa', youtubeId: '4TWR90KJl84', energyLevel: 8, noveltyTier: 'familiar' },
  { title: 'Super Shy', artist: 'NewJeans', youtubeId: 'ArmDp-zijig', energyLevel: 6, noveltyTier: 'familiar' },
  { title: 'Stronger', artist: 'Kanye West', youtubeId: 'PsO6ZnUIL0Q', energyLevel: 7, noveltyTier: 'familiar' },
  { title: 'Kick It', artist: 'NCT 127', youtubeId: 'kOHB85vDuow', energyLevel: 8, noveltyTier: 'familiar' },
  { title: 'LALALALA', artist: 'Stray Kids', youtubeId: 'd7jmi8qWY8s', energyLevel: 8, noveltyTier: 'mid' },
  { title: 'Spicy', artist: 'aespa', youtubeId: 'VZqT2s1u7kE', energyLevel: 7, noveltyTier: 'mid' },
  { title: 'ETA', artist: 'NewJeans', youtubeId: 'jOTfBlGSQFA', energyLevel: 6, noveltyTier: 'mid' },
  { title: 'Thunderous', artist: 'SEVENTEEN', youtubeId: 'HLVQ9RmsQzI', energyLevel: 8, noveltyTier: 'mid' },
  { title: 'Maestro', artist: 'SEVENTEEN', youtubeId: 'ThI0pBAb0xk', energyLevel: 7, noveltyTier: 'mid' },
  { title: 'Starry Night', artist: 'MAMAMOO', youtubeId: 'G0bRrxs-6H0', energyLevel: 6, noveltyTier: 'hidden' },
  { title: 'HIP', artist: 'MAMAMOO', youtubeId: 'o5JnEWIOaSU', energyLevel: 7, noveltyTier: 'hidden' },
  { title: 'I GOT A BOY', artist: '소녀시대', youtubeId: '6pA_Tp-D1Qw', energyLevel: 7, noveltyTier: 'hidden' },
]);
