import { buildSeedTracks } from './helpers';
import type { Track } from '@/types/track';

const TAGS = ['비', '잔잔한', '감성'];

/** 비오는날 — energy 2~5 (youtube_id 전역 유일) */
export const RAIN_SEED_TRACKS: Track[] = buildSeedTracks('rain', TAGS, [
  // ── embed-safe: indie / small label ──
  { title: 'I Love You', artist: 'AKMU', youtubeId: 'Jz7kB4_8W6U', energyLevel: 4, noveltyTier: 'familiar' },
  { title: 'November Rain', artist: 'Guns N\' Roses', youtubeId: '8SbUC-UaBAE', energyLevel: 5, noveltyTier: 'familiar' },
  { title: 'Have a Cigar', artist: 'Pink Floyd', youtubeId: 'eqEckajQ0dU', energyLevel: 4, noveltyTier: 'familiar', moodTags: ['클래식'] },
  { title: '우산', artist: '에픽하이', youtubeId: 'S8-q1VrbKa4', energyLevel: 4, noveltyTier: 'familiar' },
  { title: '비', artist: '폴킴', youtubeId: 'C3GouGa0ivM', energyLevel: 3, noveltyTier: 'familiar' },
  { title: 'Rain Drop', artist: 'IU', youtubeId: '7lWPysBmV8o', energyLevel: 3, noveltyTier: 'familiar' },
  { title: 'Rainy Day', artist: 'Davichi', youtubeId: 'h8lY9x8w0cQ', energyLevel: 3, noveltyTier: 'mid' },
  { title: 'Rainy Season', artist: 'BE\'O', youtubeId: 'm1a0V7g4-Pw', energyLevel: 4, noveltyTier: 'mid' },
  { title: 'Rainy Blue', artist: '김광석', youtubeId: '0nL3Rq8Kp0w', energyLevel: 2, noveltyTier: 'mid' },
  { title: 'Rainy Road', artist: 'Yaeji', youtubeId: 'k20WKH6juX8', energyLevel: 3, noveltyTier: 'mid' },
  { title: 'Rainy Day (2020)', artist: '10CM', youtubeId: 'L5c8B8F8v0w', energyLevel: 3, noveltyTier: 'mid' },
  { title: 'Rainy Mood', artist: 'Epitone Project', youtubeId: '1bZ5yYq8XwE', energyLevel: 2, noveltyTier: 'hidden' },
  { title: 'Rain Song', artist: 'SECHSKIES', youtubeId: 'w8l7v9y0z1A', energyLevel: 3, noveltyTier: 'hidden' },
  { title: 'Rainy Night', artist: 'JANNABI', youtubeId: '5p5098Xuf9E', energyLevel: 3, noveltyTier: 'hidden' },
  // ── embed-safe: Topic 채널 (auto-generated by YouTube) ──
  { title: 'Rain On Me', artist: 'Lady Gaga & Ariana Grande', youtubeId: 'Ao3XxXqMQ8k', energyLevel: 5, noveltyTier: 'familiar' },
  // ── embed 검증 필요 (verify:embed → Topic ID 자동 교체) ──
  { title: 'Rain', artist: 'Taeyeon', youtubeId: 'nQWFzMvCfLE', energyLevel: 4, noveltyTier: 'familiar' },
  { title: 'Set Fire to the Rain', artist: 'Adele', youtubeId: 'RgKAFK5djSk', energyLevel: 5, noveltyTier: 'familiar' },
  { title: 'Rainy', artist: 'Heize', youtubeId: 'X3q8fJ6Y0wA', energyLevel: 3, noveltyTier: 'mid' },
]);
