import { buildSeedTracks } from './helpers';
import type { Track } from '@/types/track';

const TAGS = ['우울', '감성'];

/** 우울 — energy 2~5, 잔잔→움직임→안정 흐름 */
export const SAD_SEED_TRACKS: Track[] = buildSeedTracks('sad', TAGS, [
  // ── embed-safe: indie / small label ──
  { title: '밤편지', artist: '아이유', youtubeId: 'BzYnNdJhZQw', energyLevel: 3, noveltyTier: 'familiar', moodTags: ['잔잔한', '이별'] },
  { title: '사랑이 잘 (Can\'t Love You Anymore)', artist: '악뮤', youtubeId: 'bqGTxlftbzM', energyLevel: 4, noveltyTier: 'familiar', moodTags: ['이별'] },
  { title: '비도 오고 그래서', artist: '헤이즈', youtubeId: '7EQl940qYMk', energyLevel: 4, noveltyTier: 'familiar', moodTags: ['비', '이별'] },
  { title: 'instagram', artist: 'DEAN', youtubeId: 'BvO9lTbdYRE', energyLevel: 3, noveltyTier: 'familiar', moodTags: ['잔잔한'] },
  { title: 'Empty Island', artist: '10CM', youtubeId: '6QJbs_VAflU', energyLevel: 3, noveltyTier: 'mid', moodTags: ['잔잔한'] },
  { title: 'Snow', artist: 'Zion.T', youtubeId: 'k3qyshoxe2Q', energyLevel: 3, noveltyTier: 'mid' },
  { title: '와리가티', artist: '혁오', youtubeId: '-4kQ7EOT77Q', energyLevel: 4, noveltyTier: 'mid' },
  { title: 'Wine', artist: 'Colde', youtubeId: 'wXflE5zYJc0', energyLevel: 3, noveltyTier: 'mid', moodTags: ['잔잔한'] },
  { title: 'Make Up', artist: '샘김', youtubeId: 'cMPEV8YqF0Y', energyLevel: 3, noveltyTier: 'mid' },
  { title: 'LOVE me', artist: '볼빨간사춘기', youtubeId: 'k6CuY32Yqn0', energyLevel: 4, noveltyTier: 'mid' },
  { title: 'Dance', artist: 'offonoff', youtubeId: 'p7bf2sUd3vo', energyLevel: 2, noveltyTier: 'hidden', moodTags: ['잔잔한'] },
  { title: '청춘', artist: '볼빨간사춘기', youtubeId: 'vOx2KkQmW8Y', energyLevel: 5, noveltyTier: 'familiar' },
  // ── embed-safe: Topic 채널 (auto-generated by YouTube) ──
  { title: 'Someone Like You', artist: 'Adele', youtubeId: 'UQ8cXH7qbVU', energyLevel: 3, noveltyTier: 'familiar', moodTags: ['잔잔한'] },
  { title: 'Summertime Sadness', artist: 'Lana Del Rey', youtubeId: 'fRQg_9ulGuI', energyLevel: 4, noveltyTier: 'familiar' },
  { title: '봄날', artist: '방탄소년단', youtubeId: 'ZO1xdXOXarc', energyLevel: 4, noveltyTier: 'familiar', moodTags: ['이별'] },
  // ── embed-safe: Official Audio / 검증 필요 (verify:embed 실행) ──
  { title: 'Fine', artist: '태연', youtubeId: 'Qflf2aw79G8', energyLevel: 4, noveltyTier: 'familiar', moodTags: ['이별'] },
  { title: 'Sad!', artist: 'XXXTentacion', youtubeId: 'p78fYoMBW40', energyLevel: 3, noveltyTier: 'hidden', moodTags: ['잔잔한'] },
  { title: 'Fix You', artist: 'Coldplay', youtubeId: 'k4V3Mo61fJM', energyLevel: 4, noveltyTier: 'mid', moodTags: ['이별'] },
]);
