import { buildSeedTracks } from './helpers';
import type { Track } from '@/types/track';

const TAGS = ['산책', '감성', '잔잔한'];

/** 혼자걷기 — energy 3~6, gentle-lift */
export const WALKING_SEED_TRACKS: Track[] = buildSeedTracks('walking', TAGS, [
  // ── embed-safe: indie / small label ──
  { title: 'Night Walk', artist: 'HYBS', youtubeId: 'H36g6fkmGdY', energyLevel: 3, noveltyTier: 'hidden', moodTags: ['잔잔한'] },
  { title: 'Paris in the Rain', artist: 'Lauv', youtubeId: 'kPa7bsKwL-c', energyLevel: 4, noveltyTier: 'familiar' },
  { title: 'Cherry Blossom', artist: '볼빨간사춘기', youtubeId: 'Y0pdQU87N18', energyLevel: 4, noveltyTier: 'mid' },
  { title: '사람', artist: '볼빨간사춘기', youtubeId: 'i0p1bmr0GyE', energyLevel: 4, noveltyTier: 'mid' },
  { title: '한숨', artist: '이하이', youtubeId: '7C2z4GqqS5E', energyLevel: 4, noveltyTier: 'mid' },
  { title: '기억의 밤', artist: '나얼', youtubeId: 'yP9NKnxA5gE', energyLevel: 4, noveltyTier: 'mid' },
  { title: 'You Were Beautiful', artist: 'DAY6', youtubeId: 'BS7tz2rAOSA', energyLevel: 5, noveltyTier: 'familiar' },
  { title: 'RE-BYE', artist: 'AKMU', youtubeId: 'Rf9bifrm9NM', energyLevel: 5, noveltyTier: 'familiar' },
  { title: 'Here Comes The Sun', artist: 'The Beatles', youtubeId: 'KQetboguK7o', energyLevel: 5, noveltyTier: 'familiar' },
  { title: 'Way Back Home', artist: 'SHAUN', youtubeId: '9G5Qsz7LbGU', energyLevel: 5, noveltyTier: 'mid' },
  { title: 'Traveler', artist: '우효', youtubeId: 'nXqKA8zLC3s', energyLevel: 4, noveltyTier: 'hidden' },
  { title: 'Our Paradise', artist: 'Crush', youtubeId: 'wXBxkeliOAo', energyLevel: 4, noveltyTier: 'hidden' },
  // ── embed-safe: Topic 채널 (auto-generated by YouTube) ──
  { title: 'Love poem', artist: '아이유', youtubeId: 'iOKRYIMhaDk', energyLevel: 4, noveltyTier: 'familiar' },
  { title: 'eight', artist: '아이유', youtubeId: '5_IYVichXbA', energyLevel: 4, noveltyTier: 'familiar' },
  // ── embed 검증 필요 (verify:embed → Topic ID 자동 교체) ──
  { title: 'Celebrity', artist: '아이유', youtubeId: 'OmKA9PgUm8E', energyLevel: 5, noveltyTier: 'familiar' },
  { title: 'Sunday Morning', artist: 'Maroon 5', youtubeId: 'S2Cti12XJu4', energyLevel: 5, noveltyTier: 'familiar' },
  { title: 'Polaroid Love', artist: 'ENHYPEN', youtubeId: 'Oqq97EEPFKU', energyLevel: 5, noveltyTier: 'familiar' },
  { title: '좋은 날', artist: '아이유', youtubeId: 'jeqdYqsrsA0', energyLevel: 5, noveltyTier: 'mid' },
]);
